apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-flask
  labels:
    app: sample-flask
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-flask
  template:
    metadata:
      labels:
        app: sample-flask
    spec:
      containers:
      - image: 191845259489.dkr.ecr.ap-northeast-2.amazonaws.com/sample-ecr:111
        imagePullPolicy: Always
        name: sample-flask
        ports:
        - containerPort: 5000
          protocol: TCP
